version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 3000:3000

  ui:
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
    ports:
      - 8080:8080
    environment:
      - MAILLE_API_URL=http://localhost:3000
