/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedJoinRouteImport } from './routes/_authenticated/join'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/_workspace'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/_workspace/index'
import { Route as AuthenticatedWorkspaceProjectsIndexRouteImport } from './routes/_authenticated/_workspace/projects/index'
import { Route as AuthenticatedWorkspaceMonthsIndexRouteImport } from './routes/_authenticated/_workspace/months/index'
import { Route as AuthenticatedWorkspaceCategoriesIndexRouteImport } from './routes/_authenticated/_workspace/categories/index'
import { Route as AuthenticatedWorkspaceAccountsIndexRouteImport } from './routes/_authenticated/_workspace/accounts/index'
import { Route as AuthenticatedWorkspaceProjectsIdRouteImport } from './routes/_authenticated/_workspace/projects/$id'
import { Route as AuthenticatedWorkspaceMovementsChar123IdChar125RouteImport } from './routes/_authenticated/_workspace/movements/{-$id}'
import { Route as AuthenticatedWorkspaceMonthsMonthRouteImport } from './routes/_authenticated/_workspace/months/$month'
import { Route as AuthenticatedWorkspaceActivitiesChar123IdChar125RouteImport } from './routes/_authenticated/_workspace/activities/{-$id}'
import { Route as AuthenticatedWorkspaceAccountsIdRouteImport } from './routes/_authenticated/_workspace/accounts/$id'
import { Route as AuthenticatedWorkspaceCategoriesIdIndexRouteImport } from './routes/_authenticated/_workspace/categories/$id/index'
import { Route as AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRouteImport } from './routes/_authenticated/_workspace/categories/$id/subcategories/$subcategoryId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedJoinRoute = AuthenticatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceProjectsIndexRoute =
  AuthenticatedWorkspaceProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceMonthsIndexRoute =
  AuthenticatedWorkspaceMonthsIndexRouteImport.update({
    id: '/months/',
    path: '/months/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCategoriesIndexRoute =
  AuthenticatedWorkspaceCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceAccountsIndexRoute =
  AuthenticatedWorkspaceAccountsIndexRouteImport.update({
    id: '/accounts/',
    path: '/accounts/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceProjectsIdRoute =
  AuthenticatedWorkspaceProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceMovementsChar123IdChar125Route =
  AuthenticatedWorkspaceMovementsChar123IdChar125RouteImport.update({
    id: '/movements/{-$id}',
    path: '/movements/{-$id}',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceMonthsMonthRoute =
  AuthenticatedWorkspaceMonthsMonthRouteImport.update({
    id: '/months/$month',
    path: '/months/$month',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceActivitiesChar123IdChar125Route =
  AuthenticatedWorkspaceActivitiesChar123IdChar125RouteImport.update({
    id: '/activities/{-$id}',
    path: '/activities/{-$id}',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceAccountsIdRoute =
  AuthenticatedWorkspaceAccountsIdRouteImport.update({
    id: '/accounts/$id',
    path: '/accounts/$id',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCategoriesIdIndexRoute =
  AuthenticatedWorkspaceCategoriesIdIndexRouteImport.update({
    id: '/categories/$id/',
    path: '/categories/$id/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRoute =
  AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRouteImport.update(
    {
      id: '/categories/$id/subcategories/$subcategoryId',
      path: '/categories/$id/subcategories/$subcategoryId',
      getParentRoute: () => AuthenticatedWorkspaceRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedWorkspaceIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/join': typeof AuthenticatedJoinRoute
  '/accounts/$id': typeof AuthenticatedWorkspaceAccountsIdRoute
  '/activities/{-$id}': typeof AuthenticatedWorkspaceActivitiesChar123IdChar125Route
  '/months/$month': typeof AuthenticatedWorkspaceMonthsMonthRoute
  '/movements/{-$id}': typeof AuthenticatedWorkspaceMovementsChar123IdChar125Route
  '/projects/$id': typeof AuthenticatedWorkspaceProjectsIdRoute
  '/accounts/': typeof AuthenticatedWorkspaceAccountsIndexRoute
  '/categories/': typeof AuthenticatedWorkspaceCategoriesIndexRoute
  '/months/': typeof AuthenticatedWorkspaceMonthsIndexRoute
  '/projects/': typeof AuthenticatedWorkspaceProjectsIndexRoute
  '/categories/$id/': typeof AuthenticatedWorkspaceCategoriesIdIndexRoute
  '/categories/$id/subcategories/$subcategoryId': typeof AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedWorkspaceIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/join': typeof AuthenticatedJoinRoute
  '/accounts/$id': typeof AuthenticatedWorkspaceAccountsIdRoute
  '/activities/{-$id}': typeof AuthenticatedWorkspaceActivitiesChar123IdChar125Route
  '/months/$month': typeof AuthenticatedWorkspaceMonthsMonthRoute
  '/movements/{-$id}': typeof AuthenticatedWorkspaceMovementsChar123IdChar125Route
  '/projects/$id': typeof AuthenticatedWorkspaceProjectsIdRoute
  '/accounts': typeof AuthenticatedWorkspaceAccountsIndexRoute
  '/categories': typeof AuthenticatedWorkspaceCategoriesIndexRoute
  '/months': typeof AuthenticatedWorkspaceMonthsIndexRoute
  '/projects': typeof AuthenticatedWorkspaceProjectsIndexRoute
  '/categories/$id': typeof AuthenticatedWorkspaceCategoriesIdIndexRoute
  '/categories/$id/subcategories/$subcategoryId': typeof AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/_workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/_authenticated/join': typeof AuthenticatedJoinRoute
  '/_authenticated/_workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/_authenticated/_workspace/accounts/$id': typeof AuthenticatedWorkspaceAccountsIdRoute
  '/_authenticated/_workspace/activities/{-$id}': typeof AuthenticatedWorkspaceActivitiesChar123IdChar125Route
  '/_authenticated/_workspace/months/$month': typeof AuthenticatedWorkspaceMonthsMonthRoute
  '/_authenticated/_workspace/movements/{-$id}': typeof AuthenticatedWorkspaceMovementsChar123IdChar125Route
  '/_authenticated/_workspace/projects/$id': typeof AuthenticatedWorkspaceProjectsIdRoute
  '/_authenticated/_workspace/accounts/': typeof AuthenticatedWorkspaceAccountsIndexRoute
  '/_authenticated/_workspace/categories/': typeof AuthenticatedWorkspaceCategoriesIndexRoute
  '/_authenticated/_workspace/months/': typeof AuthenticatedWorkspaceMonthsIndexRoute
  '/_authenticated/_workspace/projects/': typeof AuthenticatedWorkspaceProjectsIndexRoute
  '/_authenticated/_workspace/categories/$id/': typeof AuthenticatedWorkspaceCategoriesIdIndexRoute
  '/_authenticated/_workspace/categories/$id/subcategories/$subcategoryId': typeof AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/join'
    | '/accounts/$id'
    | '/activities/{-$id}'
    | '/months/$month'
    | '/movements/{-$id}'
    | '/projects/$id'
    | '/accounts/'
    | '/categories/'
    | '/months/'
    | '/projects/'
    | '/categories/$id/'
    | '/categories/$id/subcategories/$subcategoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/join'
    | '/accounts/$id'
    | '/activities/{-$id}'
    | '/months/$month'
    | '/movements/{-$id}'
    | '/projects/$id'
    | '/accounts'
    | '/categories'
    | '/months'
    | '/projects'
    | '/categories/$id'
    | '/categories/$id/subcategories/$subcategoryId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/_workspace'
    | '/_authenticated/join'
    | '/_authenticated/_workspace/'
    | '/_authenticated/_workspace/accounts/$id'
    | '/_authenticated/_workspace/activities/{-$id}'
    | '/_authenticated/_workspace/months/$month'
    | '/_authenticated/_workspace/movements/{-$id}'
    | '/_authenticated/_workspace/projects/$id'
    | '/_authenticated/_workspace/accounts/'
    | '/_authenticated/_workspace/categories/'
    | '/_authenticated/_workspace/months/'
    | '/_authenticated/_workspace/projects/'
    | '/_authenticated/_workspace/categories/$id/'
    | '/_authenticated/_workspace/categories/$id/subcategories/$subcategoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/join': {
      id: '/_authenticated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AuthenticatedJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_workspace': {
      id: '/_authenticated/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_workspace/': {
      id: '/_authenticated/_workspace/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/projects/': {
      id: '/_authenticated/_workspace/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedWorkspaceProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/months/': {
      id: '/_authenticated/_workspace/months/'
      path: '/months'
      fullPath: '/months/'
      preLoaderRoute: typeof AuthenticatedWorkspaceMonthsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/categories/': {
      id: '/_authenticated/_workspace/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedWorkspaceCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/accounts/': {
      id: '/_authenticated/_workspace/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AuthenticatedWorkspaceAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/projects/$id': {
      id: '/_authenticated/_workspace/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedWorkspaceProjectsIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/movements/{-$id}': {
      id: '/_authenticated/_workspace/movements/{-$id}'
      path: '/movements/{-$id}'
      fullPath: '/movements/{-$id}'
      preLoaderRoute: typeof AuthenticatedWorkspaceMovementsChar123IdChar125RouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/months/$month': {
      id: '/_authenticated/_workspace/months/$month'
      path: '/months/$month'
      fullPath: '/months/$month'
      preLoaderRoute: typeof AuthenticatedWorkspaceMonthsMonthRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/activities/{-$id}': {
      id: '/_authenticated/_workspace/activities/{-$id}'
      path: '/activities/{-$id}'
      fullPath: '/activities/{-$id}'
      preLoaderRoute: typeof AuthenticatedWorkspaceActivitiesChar123IdChar125RouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/accounts/$id': {
      id: '/_authenticated/_workspace/accounts/$id'
      path: '/accounts/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthenticatedWorkspaceAccountsIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/categories/$id/': {
      id: '/_authenticated/_workspace/categories/$id/'
      path: '/categories/$id'
      fullPath: '/categories/$id/'
      preLoaderRoute: typeof AuthenticatedWorkspaceCategoriesIdIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/_workspace/categories/$id/subcategories/$subcategoryId': {
      id: '/_authenticated/_workspace/categories/$id/subcategories/$subcategoryId'
      path: '/categories/$id/subcategories/$subcategoryId'
      fullPath: '/categories/$id/subcategories/$subcategoryId'
      preLoaderRoute: typeof AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
  }
}

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
  AuthenticatedWorkspaceAccountsIdRoute: typeof AuthenticatedWorkspaceAccountsIdRoute
  AuthenticatedWorkspaceActivitiesChar123IdChar125Route: typeof AuthenticatedWorkspaceActivitiesChar123IdChar125Route
  AuthenticatedWorkspaceMonthsMonthRoute: typeof AuthenticatedWorkspaceMonthsMonthRoute
  AuthenticatedWorkspaceMovementsChar123IdChar125Route: typeof AuthenticatedWorkspaceMovementsChar123IdChar125Route
  AuthenticatedWorkspaceProjectsIdRoute: typeof AuthenticatedWorkspaceProjectsIdRoute
  AuthenticatedWorkspaceAccountsIndexRoute: typeof AuthenticatedWorkspaceAccountsIndexRoute
  AuthenticatedWorkspaceCategoriesIndexRoute: typeof AuthenticatedWorkspaceCategoriesIndexRoute
  AuthenticatedWorkspaceMonthsIndexRoute: typeof AuthenticatedWorkspaceMonthsIndexRoute
  AuthenticatedWorkspaceProjectsIndexRoute: typeof AuthenticatedWorkspaceProjectsIndexRoute
  AuthenticatedWorkspaceCategoriesIdIndexRoute: typeof AuthenticatedWorkspaceCategoriesIdIndexRoute
  AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRoute: typeof AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
    AuthenticatedWorkspaceAccountsIdRoute:
      AuthenticatedWorkspaceAccountsIdRoute,
    AuthenticatedWorkspaceActivitiesChar123IdChar125Route:
      AuthenticatedWorkspaceActivitiesChar123IdChar125Route,
    AuthenticatedWorkspaceMonthsMonthRoute:
      AuthenticatedWorkspaceMonthsMonthRoute,
    AuthenticatedWorkspaceMovementsChar123IdChar125Route:
      AuthenticatedWorkspaceMovementsChar123IdChar125Route,
    AuthenticatedWorkspaceProjectsIdRoute:
      AuthenticatedWorkspaceProjectsIdRoute,
    AuthenticatedWorkspaceAccountsIndexRoute:
      AuthenticatedWorkspaceAccountsIndexRoute,
    AuthenticatedWorkspaceCategoriesIndexRoute:
      AuthenticatedWorkspaceCategoriesIndexRoute,
    AuthenticatedWorkspaceMonthsIndexRoute:
      AuthenticatedWorkspaceMonthsIndexRoute,
    AuthenticatedWorkspaceProjectsIndexRoute:
      AuthenticatedWorkspaceProjectsIndexRoute,
    AuthenticatedWorkspaceCategoriesIdIndexRoute:
      AuthenticatedWorkspaceCategoriesIdIndexRoute,
    AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRoute:
      AuthenticatedWorkspaceCategoriesIdSubcategoriesSubcategoryIdRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
  AuthenticatedJoinRoute: typeof AuthenticatedJoinRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
  AuthenticatedJoinRoute: AuthenticatedJoinRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
